apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{app}}-alerts
  labels:
    team: {{team}}
  namespace: {{namespace}}
spec:
  groups:
    - name: {{app}}-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="{{app}}"} == 0
          for: 1m
          annotations:
            action: "`kubectl describe pod \{{ $labels.log_pod_name }}  -n \{{ $labels.log_namespace }}` -> `kubectl logs \{{ $labels.log_pod_name }}  -n \{{ $labels.log_namespace }} `"
            summary: "App \{{ $labels.deployment }} er nede i namespace \{{ $labels.namespace }}"
          labels:
            namespace: {{namespace}}
            severity: danger

        - alert: Høy andel error i logger
          expr: sum by(log_app, log_pod_name, log_namespace) (floor(increase(logd_messages_total{log_app="{{app}}", log_level="Error"}[2m]))) > 2
          for: 2m
          annotations:
            action: "`kubectl logs \{{ $labels.log_pod_name }} -n \{{ $labels.log_namespace }}`"
            summary: "Høy andel error i logger for app \{{ $labels.log_app }} i namespace \{{ $labels.log_namespace }}"
          labels:
            namespace: {{namespace}}
            severity: danger
