apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{app}}-alerts
  labels:
    team: {{team}}
  namespace: {{namespace}}
spec:
  groups:
    - name: {{app}}-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="{{app}}"} == 0
          for: 1m
          annotations:
            action: "`Finn ut hvorfor ingen pod svarer på isAlive`"
            summary: "App \{{ $labels.deployment }} er nede i namespace \{{ $labels.namespace }}"
          labels:
            namespace: {{namespace}}
            severity: danger

        - alert: Høy andel error i logger
          expr: sum by(app, pod, namespace) (floor(increase(log_messages_errors{app="{{app}}"}[2m]))) > 1
          for: 2m
          annotations:
            action: "`Sjekk logg for app \{{ $labels.app }}`"
            summary: "Høy andel error i logger for app \{{ $labels.app }} i namespace \{{ $labels.namespace }}"
          labels:
            namespace: {{namespace}}
            severity: danger
