name: PR build and deploy

on:
  pull_request:

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut
        uses: actions/checkout@v3
        with:
          ref: ${{env.COMMIT_SHA}}
      - name: Setter opp java
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: Kjører test og bygg
        run: ./gradlew test shadowJar
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
