name: PR bygg og test

on:
  pull_request:

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  build:
    name: Bygg og test kode
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut
        uses: actions/checkout@v3
        with:
          ref: ${{env.COMMIT_SHA}}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cacher gradle artifakter
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Kjører test og bygg
        run: ./gradlew test shadowJar
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
